# Cloud Build configuration for Dungeon Master's Oracle
# Implements automated CI/CD pipeline for container builds and deployments

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'docker/Dockerfile',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/dm-oracle:${SHORT_SHA}',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/dm-oracle:latest',
      '.'
    ]
    id: 'build-image'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/dm-oracle:${SHORT_SHA}'
    ]
    id: 'push-image-sha'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/dm-oracle:latest'
    ]
    id: 'push-image-latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/dm-oracle:${SHORT_SHA}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--service-account', '${_SERVICE_ACCOUNT}',
      '--set-env-vars', 'PROJECT_ID=${PROJECT_ID}',
      '--set-env-vars', 'DATASET_ID=${_DATASET_ID}',
      '--set-env-vars', 'TABLE_ID=${_TABLE_ID}',
      '--set-env-vars', 'DATA_BUCKET=${_DATA_BUCKET}',
      '--set-env-vars', 'ENVIRONMENT=${_ENVIRONMENT}',
      '--set-secrets', 'GOOGLE_API_KEY=google-api-key:latest',
      '--memory', '2Gi',
      '--cpu', '2',
      '--min-instances', '0',
      '--max-instances', '10',
      '--timeout', '300s',
      '--port', '8080'
    ]
    id: 'deploy-cloud-run'

# Substitutions (variables) used in the build
substitutions:
  _REGION: 'us-central1'
  _REPOSITORY: 'dm-oracle-images'
  _SERVICE_NAME: 'dm-oracle-api'
  _SERVICE_ACCOUNT: 'dm-oracle-service-account@${PROJECT_ID}.iam.gserviceaccount.com'
  _DATASET_ID: 'dnd_data'
  _TABLE_ID: 'monsters'
  _DATA_BUCKET: 'your-data-bucket-name'  # Update this with your actual bucket name
  _ENVIRONMENT: 'production'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Higher CPU for building ML dependencies
  substitutionOption: 'ALLOW_LOOSE'

# Build timeout (30 minutes)
timeout: '1800s'

# Trigger configuration
# This build will be triggered on:
# - Push to main branch
# - Manual trigger from Cloud Console or gcloud CLI 